### ISSUE TITLE
NullPointerException in LAInterpolator.AnnotInfo.color

### ISSUE THREAD

**Issue by PhilippWendler** [juergenchrist/smtinterpol#4]
This [file](https://gist.github.com/PhilippWendler/2059dab674d96367771f#file-smtinterpol-npe-lainterpolor-color-smt2) created by CPAchecker produces a NullPointerException with current SMTInterpol:

```
java.lang.NullPointerException
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.LAInterpolator$AnnotInfo.color(LAInterpolator.java:81)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.LAInterpolator$AnnotInfo.<init>(LAInterpolator.java:63)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.LAInterpolator.computeAuxAnnotations(LAInterpolator.java:163)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.LAInterpolator.computeAuxAnnotations(LAInterpolator.java:169)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.LAInterpolator.computeInterpolants(LAInterpolator.java:426)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.interpolate(Interpolator.java:568)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.interpolate(Interpolator.java:462)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.getInterpolants(Interpolator.java:262)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:1211)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:1998)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:853)        at java_cup.runtime.LRParser.parse(Unknown Source)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:129)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:114)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:36)
        at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:180)
```

**Comment by PhilippWendler** [comment]
Thanks, this fixes the problem.
