### ISSUE TITLE
NullPointerException in MutableInfinitNumber.compareTo

### ISSUE THREAD

**Issue by agacek** [juergenchrist/smtinterpol#6]
I'm using version 2.1-217-g6d15196.

The following check-sat query causes a NullPointerException

```
(set-logic QF_UFLIRA)
(set-option :verbosity 2)
(declare-fun x () Real)
(assert (not (= (div (to_int x) 5) (to_int (/ x 5)))))
(check-sat)
```

```
java.lang.NullPointerException
	at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.linar.MutableInfinitNumber.compareTo(MutableInfinitNumber.java:147)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.linar.LinArSolve.choose(LinArSolve.java:2116)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.linar.LinArSolve.mutate(LinArSolve.java:1883)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.theory.linar.LinArSolve.computeConflictClause(LinArSolve.java:609)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.checkConsistency(DPLLEngine.java:901)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.dpll.DPLLEngine.solve(DPLLEngine.java:1039)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol$CheckType$1.check(SMTInterpol.java:98)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.checkSat(SMTInterpol.java:759)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser$Action$.CUP$do_action(Parser.java:1963)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.Parser.do_action(Parser.java:853)
	at java_cup.runtime.LRParser.parse(Unknown Source)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseStream(ParseEnvironment.java:129)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.ParseEnvironment.parseScript(ParseEnvironment.java:114)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTLIB2Parser.run(SMTLIB2Parser.java:40)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.Main.main(Main.java:182)
```

**Comment by agacek** [comment]
I got the same exception on this file:

  https://gist.github.com/agacek/f8cd18d25efe10b7ef85
